/* Generated By:JJTree: Do not edit this line. ASTBINARY_OP.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBINARY_OP extends SimpleNode {
  public ASTBINARY_OP(int id) {
    super(id);
  }

  public ASTBINARY_OP(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4cd27a3ebb9d336184e83c8da89561c0 (do not edit this line) */
