/* Generated By:JJTree: Do not edit this line. ASTClass.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClass extends SimpleNode {
  public ASTClass(int id) {
    super(id);
  }

  public ASTClass(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5f6cd112724769496d8223b07baf40bb (do not edit this line) */
