/* Generated By:JJTree: Do not edit this line. ASTMain.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMain extends SimpleNode {
  public ASTMain(int id) {
    super(id);
  }

  public ASTMain(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a85880001ea7c3812ae2f164a60c4be0 (do not edit this line) */
