/* Generated By:JJTree: Do not edit this line. ASTVar.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVar extends SimpleNode {
  public ASTVar(int id) {
    super(id);
  }

  public ASTVar(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c81fe0eff35529855cdc3e0b7fea26cc (do not edit this line) */
