/* Generated By:JJTree: Do not edit this line. ASTADD.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package src.AST;

public
class ASTADD extends SimpleNode {
  public ASTADD(int id) {
    super(id);
  }

  public ASTADD(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9844ed4d90077456326d709c50eb9827 (do not edit this line) */
