/* Generated By:JJTree: Do not edit this line. ASTArrayAssign.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package src.AST;

public
class ASTArrayAssign extends SimpleNode {
  public ASTArrayAssign(int id) {
    super(id);
  }

  public ASTArrayAssign(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d6054771fa6262a7178f1b0ad2693f26 (do not edit this line) */
