/* Generated By:JJTree: Do not edit this line. ASTAND.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTAND extends SimpleNode {
  public ASTAND(int id) {
    super(id);
  }

  public ASTAND(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f12b26cdfa9f625fc12cbe5cc7c17e91 (do not edit this line) */
