/* Generated By:JJTree: Do not edit this line. ASTASSIGN.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;


public
class ASTASSIGN extends SimpleNode {
  public ASTASSIGN(int id) {
    super(id);
  }

  public ASTASSIGN(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=44a56ebc5ea18729019b75dcebd62514 (do not edit this line) */
