/* Generated By:JJTree: Do not edit this line. ASTClass.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTClass extends SimpleNode {
  public ASTClass(int id) {
    super(id, true);
  }

  public ASTClass(Program p, int id) {
    super(p, id, true);
  }

  public boolean analyse(){
    this.symbols = getNodeSymbolTable();
    this.methods = getNodeMethodTable();

    //TODO Iterate children to get both the variable declaractions and the method signatures
    return true;
  }

}
/* JavaCC - OriginalChecksum=8a9dc2db515203387b264bd6aa6bee4b (do not edit this line) */
