/* Generated By:JJTree: Do not edit this line. ASTCONDITION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTCONDITION extends SimpleNode {
  public ASTCONDITION(int id) {
    super(id);
  }

  public ASTCONDITION(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8521363d6540f1dacb01854bed3d25b0 (do not edit this line) */
