/* Generated By:JJTree: Do not edit this line. ASTClass.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public class ASTClass extends SimpleNode {
	public ASTClass(int id) {
		super(id, true, true);
	}

	public ASTClass(Program p, int id) {
		super(p, id, true, true);
	}

	public boolean analyse() {
		this.symbols = getNodeSymbolTable();
		this.methods = getNodeMethodTable();
		Node[] children = getChildren();

		boolean success = true;

		if (children == null)
			return false;

		for (Node child : children) {

			if (((SimpleNode) child).getNodeString().equals("Method"))
				success = ((ASTMethod) child).addNewMethod();

			else if (((SimpleNode) child).getNodeString().equals("Var"))
				success = ((ASTVar) child).analyse();
		}

		for (Node child : children) {

			if (((SimpleNode) child).getNodeString().equals("Method"))
				success = ((ASTMethod) child).analyse();

		}

		return success;
	}

}
/*
 * JavaCC - OriginalChecksum=8a9dc2db515203387b264bd6aa6bee4b (do not edit this
 * line)
 */
