/* Generated By:JJTree: Do not edit this line. ASTEXCLAMATION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTEXCLAMATION extends SimpleNode {
  public ASTEXCLAMATION(int id) {
    super(id);
  }

  public ASTEXCLAMATION(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=43c455cd7054c402c14aabb17df89b99 (do not edit this line) */
