/* Generated By:JJTree: Do not edit this line. ASTExclamation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTExclamation extends SimpleNode {
  public ASTExclamation(int id) {
    super(id);
  }

  public ASTExclamation(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9a1f9ea61fadccc446f3dd69d731e612 (do not edit this line) */
