/* Generated By:JJTree: Do not edit this line. ASTEXCLAMATION_MARK.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTEXCLAMATION_MARK extends SimpleNode {
  public ASTEXCLAMATION_MARK(int id) {
    super(id);
  }

  public ASTEXCLAMATION_MARK(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3ce70d12901746ca7360d95944396950 (do not edit this line) */
