/* Generated By:JJTree: Do not edit this line. ASTIF_BODY.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTIF_BODY extends SimpleNode {
  public ASTIF_BODY(int id) {
    super(id);
  }

  public ASTIF_BODY(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d1bb78de15ad474dbd4b6de9a9750db3 (do not edit this line) */
