/* Generated By:JJTree: Do not edit this line. ASTLESS_THAN.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

import src.semantic.Symbol;
import src.semantic.Symbol.Type;

public class ASTLESS_THAN extends SimpleNode {
    public ASTLESS_THAN(int id) {
        super(id);
    }

    public ASTLESS_THAN(Program p, int id) {
        super(p, id);
    }

    public Symbol.Type getReturnType() {
        return Symbol.Type.BOOLEAN;
    }

    public boolean checkSymbolTable() {

        if (getChildren().length != 2) {
            printSemanticError("Not valid LESS_THAN operands");
            return false;
        }

        for (Node child : getChildren())
            ((SimpleNode) child).checkSymbolTable();

        SimpleNode left_child = (SimpleNode) this.jjtGetChild(0);
        SimpleNode right_child = (SimpleNode) this.jjtGetChild(1);

        Symbol.Type lop_type = left_child.getReturnType();

        if (lop_type.equals(Symbol.Type.VOID))
            lop_type = getVarType(left_child.getName());

        if (!lop_type.equals(Symbol.Type.INT)) {
            printSemanticError("Invalid type for left operand");
            return false;
        }

        Symbol.Type rop_type = right_child.getReturnType();

        // System.out.println("rop: " + rop_type);
        if (rop_type.equals(Symbol.Type.VOID)) {

            if ((right_child.getId()) == (ProgramTreeConstants.JJTPERIOD))
                rop_type = lop_type;
            else
                rop_type = getVarType(right_child.getName());
        }

        if (!rop_type.equals(Symbol.Type.INT)) {
            printSemanticError("Invalid type for right operand");
            return false;
        }

        return true;
    }

}
/*
 * JavaCC - OriginalChecksum=ad5070dad0f02986ae4d465bccb34115 (do not edit this
 * line)
 */
