/* Generated By:JJTree: Do not edit this line. ASTLESS_THAN.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTLESS_THAN extends SimpleNode {
  public ASTLESS_THAN(int id) {
    super(id);
  }

  public ASTLESS_THAN(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ad5070dad0f02986ae4d465bccb34115 (do not edit this line) */
