/* Generated By:JJTree: Do not edit this line. ASTMUL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTMUL extends SimpleNode {
  public ASTMUL(int id) {
    super(id);
  }

  public ASTMUL(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=922caef4ea363c4951a74af871fffff8 (do not edit this line) */
