/* Generated By:JJTree: Do not edit this line. ASTNEW.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTNEW extends SimpleNode {
  public ASTNEW(int id) {
    super(id);
  }

  public ASTNEW(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=233b22a74042f46f806eeffdd8b622c1 (do not edit this line) */
