/* Generated By:JJTree: Do not edit this line. ASTPERIOD.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTPERIOD extends SimpleNode {
  public ASTPERIOD(int id) {
    super(id);
  }

  public ASTPERIOD(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ceda7f0b7d22d82a4a9eea22a05d4678 (do not edit this line) */
