/* Generated By:JJTree: Do not edit this line. ASTRETURN.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

import src.semantic.*;

public class ASTRETURN extends SimpleNode {
    public ASTRETURN(int id) {
        super(id);
    }

    public ASTRETURN(Program p, int id) {
        super(p, id);
    }

}
/*
 * JavaCC - OriginalChecksum=a25a7460b68f1e51ef6fbb9c25d95cca (do not edit this
 * line)
 */
