/* Generated By:JJTree: Do not edit this line. ASTskip_to.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTskip_to extends SimpleNode {
  public ASTskip_to(int id) {
    super(id);
  }

  public ASTskip_to(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=61782231fd6ef04eb0fab552f156770c (do not edit this line) */
