/* Generated By:JJTree: Do not edit this line. ASTSUB.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTSUB extends SimpleNode {
  public ASTSUB(int id) {
    super(id);
  }

  public ASTSUB(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5b7c4f489561ccfe04bd8afceed1759 (do not edit this line) */
