/* Generated By:JJTree: Do not edit this line. ASTWHILE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTWHILE extends SimpleNode {
  public ASTWHILE(int id) {
    super(id);
  }

  public ASTWHILE(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7acb334667063b8994cd12f75c1244bf (do not edit this line) */
