/* Generated By:JavaCC: Do not edit this line. ProgramTreeConstants.java Version 6.0_1 */
package src.AST;

public interface ProgramTreeConstants
{
  public int JJTSKIP_TO = 0;
  public int JJTPROGRAM = 1;
  public int JJTCLASS = 2;
  public int JJTEXTENDS = 3;
  public int JJTVAR = 4;
  public int JJTMAIN = 5;
  public int JJTMETHOD = 6;
  public int JJTVOID = 7;
  public int JJTARGUMENT = 8;
  public int JJTRETURN = 9;
  public int JJTIF = 10;
  public int JJTELSE = 11;
  public int JJTWHILE = 12;
  public int JJTASSIGN = 13;
  public int JJTIDENTIFIER = 14;
  public int JJTADD = 15;
  public int JJTSUB = 16;
  public int JJTMUL = 17;
  public int JJTDIV = 18;
  public int JJTAND = 19;
  public int JJTLESS_THAN = 20;
  public int JJTEXCLAMATION_MARK = 21;
  public int JJTPERIOD = 22;
  public int JJTTERM = 23;
  public int JJTPERIODAUX = 24;
  public int JJTNEW = 25;


  public String[] jjtNodeName = {
    "skip_to",
    "Program",
    "Class",
    "Extends",
    "Var",
    "Main",
    "Method",
    "void",
    "Argument",
    "RETURN",
    "IF",
    "ELSE",
    "WHILE",
    "ASSIGN",
    "Identifier",
    "ADD",
    "SUB",
    "MUL",
    "DIV",
    "AND",
    "LESS_THAN",
    "EXCLAMATION_MARK",
    "PERIOD",
    "Term",
    "PeriodAux",
    "NEW",
  };
}
/* JavaCC - OriginalChecksum=bb677fb10c5909ebff8fb7e86bbddb1e (do not edit this line) */
