/* Generated By:JavaCC: Do not edit this line. ProgramTreeConstants.java Version 5.0 */
package src.AST;

public interface ProgramTreeConstants
{
  public int JJTSKIP_TO = 0;
  public int JJTPROGRAM = 1;
  public int JJTCLASS = 2;
  public int JJTEXTENDS = 3;
  public int JJTVAR = 4;
  public int JJTMAIN = 5;
  public int JJTMETHOD = 6;
  public int JJTVOID = 7;
  public int JJTARGUMENT = 8;
  public int JJTRETURN = 9;
  public int JJTCONDITION = 10;
  public int JJTBODY = 11;
  public int JJTIF = 12;
  public int JJTELSE = 13;
  public int JJTWHILE = 14;
  public int JJTASSIGN = 15;
  public int JJTIDENTIFIER = 16;
  public int JJTADD = 17;
  public int JJTSUB = 18;
  public int JJTMUL = 19;
  public int JJTDIV = 20;
  public int JJTAND = 21;
  public int JJTLESS_THAN = 22;
  public int JJTEXCLAMATION = 23;
  public int JJTPERIOD = 24;
  public int JJTTERM = 25;
  public int JJTPERIODAUX = 26;
  public int JJTNEW = 27;


  public String[] jjtNodeName = {
    "skip_to",
    "Program",
    "Class",
    "Extends",
    "Var",
    "Main",
    "Method",
    "void",
    "Argument",
    "RETURN",
    "CONDITION",
    "BODY",
    "IF",
    "ELSE",
    "WHILE",
    "ASSIGN",
    "Identifier",
    "ADD",
    "SUB",
    "MUL",
    "DIV",
    "AND",
    "LESS_THAN",
    "EXCLAMATION",
    "PERIOD",
    "Term",
    "PeriodAux",
    "NEW",
  };
}
/* JavaCC - OriginalChecksum=3204c09866f7b62298535539a7f4ab1c (do not edit this line) */
