/* Generated By:JJTree: Do not edit this line. ASTArrayIndex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTArrayIndex extends SimpleNode {
  public ASTArrayIndex(int id) {
    super(id);
  }

  public ASTArrayIndex(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=60692831d3a8fc11e8db4ea7f9c99ec7 (do not edit this line) */
