/* Generated By:JJTree: Do not edit this line. ASTAUX.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTAUX extends SimpleNode {
  public ASTAUX(int id) {
    super(id);
  }

  public ASTAUX(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1b2f8a8b7a3b1e9498d8705e29690a94 (do not edit this line) */
