/* Generated By:JJTree: Do not edit this line. ASTArgument.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package src.AST;

import src.semantic.*;

public class ASTArgument extends SimpleNode {
    public ASTArgument(int id) {
        super(id);
    }

    public ASTArgument(Program p, int id) {
        super(p, id);
    }

    public Symbol.Type getArgumentType() {
        Symbol.Type type = this.getReturnType();
        
        if(isTypeValidForVar(type))
            return type;
        else
            return Symbol.Type.UNDEFINED;
    }

}
/*
 * JavaCC - OriginalChecksum=42d14b8a3bb371e133304e73a2a9236f (do not edit this
 * line)
 */
