/* Generated By:JJTree: Do not edit this line. ASTBODY.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTBODY extends SimpleNode {
  public ASTBODY(int id) {
    super(id);
  }

  public ASTBODY(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0805e49d851638a0b9828ff62364a697 (do not edit this line) */
