/* Generated By:JJTree: Do not edit this line. ASTEXCLM_MARK.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTEXCLM_MARK extends SimpleNode {
  public ASTEXCLM_MARK(int id) {
    super(id);
  }

  public ASTEXCLM_MARK(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f2b516bf2eb50cd04ab8796d28df2795 (do not edit this line) */
