/* Generated By:JJTree: Do not edit this line. ASTExtends.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTExtends extends SimpleNode {
  public ASTExtends(int id) {
    super(id);
  }

  public ASTExtends(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9d5da6f38aa8657ed3fcdc0de9bab86f (do not edit this line) */
