/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public class ASTIdentifier extends SimpleNode {
    
    public ASTIdentifier(int id) {
        super(id);
    }

    public ASTIdentifier(Program p, int id) {
        super(p, id);
    }

    public boolean isArrayAccess() {
        return this.jjtGetNumChildren() != 0;
    }

}
/*
 * JavaCC - OriginalChecksum=b1126123a0fcee43aed39e2c12ff89a7 (do not edit this
 * line)
 */
