/* Generated By:JJTree: Do not edit this line. ASTNewAux.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTNewAux extends SimpleNode {
  public ASTNewAux(int id) {
    super(id);
  }

  public ASTNewAux(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d1d54be23dce2d4271244cff65a7a3f1 (do not edit this line) */
