/* Generated By:JJTree: Do not edit this line. ASTPeriodAux.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTPeriodAux extends SimpleNode {
  public ASTPeriodAux(int id) {
    super(id);
  }

  public ASTPeriodAux(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7b07afb222d79b412392fa5b1ead9728 (do not edit this line) */
