/* Generated By:JJTree: Do not edit this line. ASTWHILE_BODY.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.AST;

public
class ASTWHILE_BODY extends SimpleNode {
  public ASTWHILE_BODY(int id) {
    super(id);
  }

  public ASTWHILE_BODY(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6e7946dab11665ba41c7b82870071d4e (do not edit this line) */
